apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-example
    env: stage
    type: app
  name: cicd-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-example
      env: stage
      type: app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cicd-example
        env: stage
        type: app
    spec:
      containers:
        - name: cicd-example
          image: 'rafarlopes/cicd-example:a0ba51a'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
